services:
  frontend:
    image: node:22-alpine
    working_dir: /app
    container_name: frontend
    env_file:
      - .env
    volumes:
      - .:/app
      - frontend:/app/dist
    command: sh -c "npm install && npm run build || exit 0"

volumes:
  frontend:
