"""add uid to souls

Revision ID: 036ed58dcef9
Revises: b5956e17c65e
Create Date: 2026-05-19 04:12:45.779367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036ed58dcef9'
down_revision: Union[str, Sequence[str], None] = 'b5956e17c65e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('uid', sa.String(), nullable=False))
    op.create_index(op.f('ix_inquiries_uid'), 'inquiries', ['uid'], unique=True)
    op.add_column('souls', sa.Column('uid', sa.String(), nullable=False))
    op.create_index(op.f('ix_souls_uid'), 'souls', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_souls_uid'), table_name='souls')
    op.drop_column('souls', 'uid')
    op.drop_index(op.f('ix_inquiries_uid'), table_name='inquiries')
    op.drop_column('inquiries', 'uid')
    # ### end Alembic commands ###
