"""change_column_to_integer

Revision ID: 0c1e91bc9d33
Revises: 349ae278d899
Create Date: 2026-06-09 09:38:13.301143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1e91bc9d33'
down_revision: Union[str, Sequence[str], None] = '349ae278d899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inquiries', 'order_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="order_id::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inquiries', 'order_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using="order_id::varchar")
    # ### end Alembic commands ###
