"""change field name in soul and inquiry table to match standard

Revision ID: 14559446556e
Revises: d7adaf83c2a8
Create Date: 2026-06-09 04:26:58.951687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14559446556e'
down_revision: Union[str, Sequence[str], None] = 'd7adaf83c2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('inquiries', sa.Column('text', sa.Text(), nullable=False))
    op.drop_index(op.f('ix_inquiries_uid'), table_name='inquiries')
    op.create_index(op.f('ix_inquiries_user_id'), 'inquiries', ['user_id'], unique=False)
    op.drop_column('inquiries', 'uid')
    op.drop_column('inquiries', 'inquiry_text')
    op.add_column('souls', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('souls', sa.Column('text', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_souls_uid'), table_name='souls')
    op.create_index(op.f('ix_souls_user_id'), 'souls', ['user_id'], unique=True)
    op.drop_column('souls', 'bio_essay')
    op.drop_column('souls', 'uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('souls', sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('souls', sa.Column('bio_essay', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_souls_user_id'), table_name='souls')
    op.create_index(op.f('ix_souls_uid'), 'souls', ['uid'], unique=True)
    op.drop_column('souls', 'text')
    op.drop_column('souls', 'user_id')
    op.add_column('inquiries', sa.Column('inquiry_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('inquiries', sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_inquiries_user_id'), table_name='inquiries')
    op.create_index(op.f('ix_inquiries_uid'), 'inquiries', ['uid'], unique=False)
    op.drop_column('inquiries', 'text')
    op.drop_column('inquiries', 'user_id')
    # ### end Alembic commands ###
