"""update soul field in DB from user_id to insider_id

Revision ID: 349ae278d899
Revises: 14559446556e
Create Date: 2026-06-09 08:19:52.093720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349ae278d899'
down_revision: Union[str, Sequence[str], None] = '14559446556e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('souls', sa.Column('insider_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_souls_user_id'), table_name='souls')
    op.create_index(op.f('ix_souls_insider_id'), 'souls', ['insider_id'], unique=True)
    op.drop_column('souls', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('souls', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_souls_insider_id'), table_name='souls')
    op.create_index(op.f('ix_souls_user_id'), 'souls', ['user_id'], unique=True)
    op.drop_column('souls', 'insider_id')
    # ### end Alembic commands ###
