"""change user_id to client_id

Revision ID: 3faac93f4f00
Revises: 0c1e91bc9d33
Create Date: 2026-06-09 10:31:18.443278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3faac93f4f00'
down_revision: Union[str, Sequence[str], None] = '0c1e91bc9d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('client_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_inquiries_user_id'), table_name='inquiries')
    op.create_index(op.f('ix_inquiries_client_id'), 'inquiries', ['client_id'], unique=False)
    op.drop_column('inquiries', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_inquiries_client_id'), table_name='inquiries')
    op.create_index(op.f('ix_inquiries_user_id'), 'inquiries', ['user_id'], unique=False)
    op.drop_column('inquiries', 'client_id')
    # ### end Alembic commands ###
