"""fresh_baseline_schema

Revision ID: 7d7d0577c97f
Revises: 036ed58dcef9
Create Date: 2026-05-26 00:05:47.246623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7d0577c97f'
down_revision: Union[str, Sequence[str], None] = '036ed58dcef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('query', sa.Text(), nullable=True))
    op.add_column('souls', sa.Column('soul', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('souls', 'soul')
    op.drop_column('inquiries', 'query')
    # ### end Alembic commands ###
