"""edit inquiry uid to be not unique

Revision ID: d7adaf83c2a8
Revises: fdf2445942b0
Create Date: 2026-05-26 12:57:40.214832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7adaf83c2a8'
down_revision: Union[str, Sequence[str], None] = 'fdf2445942b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inquiries_uid'), table_name='inquiries')
    op.create_index(op.f('ix_inquiries_uid'), 'inquiries', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inquiries_uid'), table_name='inquiries')
    op.create_index(op.f('ix_inquiries_uid'), 'inquiries', ['uid'], unique=True)
    # ### end Alembic commands ###
