"""edit inquiry table to have order_id

Revision ID: fdf2445942b0
Revises: 7d7d0577c97f
Create Date: 2026-05-26 12:53:44.740257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf2445942b0'
down_revision: Union[str, Sequence[str], None] = '7d7d0577c97f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('order_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inquiries', 'order_id')
    # ### end Alembic commands ###
