
  # --- 2. MICROSERVICES ---
  identity-svc:
    ports:
      - 8000:8000
    container_name: identity-svc
    volumes:
      - ../services/identity:/app
    build: ../services/identity
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DB_HOST=database
      - DB_USER=user
      - DB_NAME=identity
      - DB_PASS=hello
    networks:
      - frontend
      - backend

  ledger-mock:
    image: stoplight/prism:4
    command: mock -h 0.0.0.0 /public/api.yaml
    volumes:
      - ./services/ledger/openapi.yaml:/public/api.yaml:ro
    ports:
      - "8001:4010" # Host 8001 maps to Prism's default port 4010
    networks:
      - backend

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../${VOLUMES_PATH}/database/

secrets:
  db_password:
    file: ../secrets/dev/db_password.txt
