name: vekko

include:
  # - ./backend/docker-compose.yml
  # - ./frontend/docker-compose.yml
  # - ./services/identity/docker-compose.yml

  - ./infra/nginx/docker-compose.yml
  # - ./infra/postgres/docker-compose.yml

  - ./infra/grafana/docker-compose.yml
  # - ./infra/prometheus/docker-compose.yml
  # - ./infra/node-exporter/docker-compose.yml

  # - ./infra/kibana/docker-compose.yml
  # - ./infra/elasticsearch/docker-compose.yml
  # - ./infra/logstash/docker-compose.yml
  # - ./infra/filebeat/docker-compose.yml
  # - ./infra/mitmproxy/docker-compose.yml

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge

# volumes:
#   database:
#     name: database
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ../${VOLUMES_PATH}/database/

secrets:
  db_password:
    file: ../secrets/dev/db_password.txt
