name: vekko

include:
  # - ./web/docker-compose.yml
  # - ./frontend/docker-compose.yml
  # - ./services/identity/docker-compose.yml
  # - ./services/interaction/docker-compose.yml
  # - ./services/ledger/docker-compose.yml
  # - ./services/semantic/docker-compose.yml

  - ./infra/nginx/docker-compose.yml
  - ./infra/grafana/docker-compose.yml
  - ./infra/prometheus/docker-compose.yml
  - ./infra/kibana/docker-compose.yml
  - ./infra/elasticsearch/docker-compose.yml

services:
  ledger:
    build:
      context: .
      dockerfile: services/ledger/Dockerfile
    container_name: ledger
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=ledger_user
      - DB_NAME=ledger_db
      - DB_PASS_FILE=/run/secrets/postgres_ledger_pass
    secrets:
      - postgres_ledger_pass
    depends_on:
      - postgres
    restart: always
    networks:
      - backend  # Fix: Ensure this is indented under 'ledger'

# Root level keys must have ZERO indentation
secrets:
  postgres_ledger_pass:
    file: ./secrets/postgres_ledger_pass

volumes:
  postgres_data: 

networks:
  web:
    name: web
    driver: bridge
