services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    container_name: filebeat
    entrypoint: ["/bin/bash", "/usr/local/bin/entrypoint-wrapper.sh"]
    command: ["--strict.perms=false", "-e", "-d", "publish", "-v"]
    user: root
    privileged: true
    labels:
      co.elastic.logs/enabled: "false"
    environment:
      LOGGING_LEVEL: debug
      KIBANA: "kibana:5601"
      ELASTICSEARCH: "elasticsearch:9200"
      LOGSTASH: "logstash:5044"
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -f http://localhost:5066/stats >/dev/null || exit 1",
        ]
      interval: 10s
      timeout: 15s
      retries: 500
      start_period: 10s
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /goinfre/${USER}/docker/containers:/var/lib/docker/containers:ro
      - ./init.sh:/usr/share/filebeat/init.sh:ro
      - ./entrypoint-wrapper.sh:/usr/local/bin/entrypoint-wrapper.sh:ro
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock:ro
      - ./policy.json:/usr/share/filebeat/policy.json:ro
      - filebeat_data:/usr/share/filebeat/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
      logstash:
        condition: service_healthy

volumes:
  filebeat_data:
