filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        enabled: true
        type: filestream
        parsers:
          - container: ~
        paths:
          - "/var/lib/docker/containers/${data.container.id}/*.log"

# output.console:
#   pretty: true

output.logstash:
  hosts: ["${LOGSTASH:logstash:5044}"]

setup.kibana:
  host: "${KIBANA:kibana:5601}"

setup.elasticsearch:
  hosts: ["${ELASTICSEARCH:elasticsearch:9200}"]

http:
  enabled: true
  host: localhost
  port: 5066
