events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    # If mime.types is missing or broken, this serves as a fallback
    default_type  application/octet-stream;

    server {
        listen 80;
        # 1. Ensure this path contains your index.html AND assets folder
        root /usr/share/nginx/html;
        index index.html;

        # 2. Handle the main Vue App and Routing
        location / {
            try_files $uri $uri/ /index.html;
        }

        # 3. Handle JavaScript specifically with strict MIME types
        location ~* \.js$ {
            # This is the standard way to define the type inside a block
            include /etc/nginx/mime.types;
            default_type application/javascript;
            
            expires 1y;
            add_header Cache-Control "public, no-transform";
            # Critical: prevent it from falling back to index.html
            try_files $uri =404;
        }

        # 4. Handle other static assets
        location ~* \.(css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 1y;
            add_header Cache-Control "public, no-transform";
            try_files $uri =404;
        }

        location = /grafana {
            return 301 $scheme://$http_host/grafana/;
        }
        location ^~ /grafana/ {
            # 1. Basic Auth
            auth_basic "Restricted Access";
            auth_basic_user_file /run/secrets/htpasswd;
            proxy_set_header Authorization "";
            proxy_pass http://grafana:3000; 
            
            # 3. Essential Headers for Grafana
            proxy_set_header Host $http_host; # Includes the port (8080)
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location = /prometheus {
            return 301 $scheme://$http_host/prometheus/;
        }
        location ^~ /prometheus/ {
            auth_basic "Metrics Access";
            auth_basic_user_file /run/secrets/htpasswd;

            proxy_pass http://prometheus:9090/; # Default Prometheus port
            
            proxy_set_header Host $http_host; # Includes the port (8080)
            proxy_set_header X-Real-IP $remote_addr;
        }
    
        location = /kibana {
            return 301 $scheme://$http_host/kibana/;
        }
        location ^~ /kibana/ {
            auth_basic "Log Access";
            auth_basic_user_file /run/secrets/htpasswd;

            proxy_pass http://kibana:5601; # Default Kibana port
            

            proxy_set_header Host $http_host; # Includes the port (8080)
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }
    }
}
