"""add purchase table

Revision ID: f1e89dbaae6b
Revises: fff0e68e4299
Create Date: 2026-05-19 04:08:23.886650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e89dbaae6b'
down_revision = 'fff0e68e4299'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###