"""create matches table

Revision ID: 5ec09920cc5f
Revises: 93221fa5a287
Create Date: 2026-05-17 15:16:47.115846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec09920cc5f'
down_revision: Union[str, Sequence[str], None] = '93221fa5a287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('insider_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_insider_id'), 'matches', ['insider_id'], unique=False)
    op.create_index(op.f('ix_matches_order_id'), 'matches', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_order_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_insider_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
