"""update matches table

Revision ID: c692437a330f
Revises: 1805d5b92ae6
Create Date: 2026-05-19 16:54:00.021242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c692437a330f"
down_revision: Union[str, Sequence[str], None] = "1805d5b92ae6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("score_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "score_id")
    # ### end Alembic commands ###
