openapi: 3.1.0
info:
  title: Interaction Service API
  description: Microservice for Interaction
  version: 1.0.0
paths:
  /api/v1/orders/:
    post:
      tags:
      - orders
      summary: Create Order
      operationId: create_order_api_v1_orders__post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderCreate'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderRead'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    get:
      tags:
      - orders
      summary: Get Orders
      operationId: get_orders_api_v1_orders__get
      parameters:
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          maximum: 50
          minimum: 1
          default: 20
          title: Limit
      - name: offset
        in: query
        required: false
        schema:
          type: integer
          maximum: 10
          minimum: 0
          default: 0
          title: Offset
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderRead'
                title: Response Get Orders Api V1 Orders  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/orders/{order_id}:
    get:
      tags:
      - orders
      summary: Get Order
      operationId: get_order_api_v1_orders__order_id__get
      parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          title: Order Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderRead'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - orders
      summary: Delete Order
      operationId: delete_order_api_v1_orders__order_id__delete
      parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          title: Order Id
      responses:
        '204':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    patch:
      tags:
      - orders
      summary: Update Order
      operationId: update_order_api_v1_orders__order_id__patch
      parameters:
      - name: order_id
        in: path
        required: true
        schema:
          type: integer
          title: Order Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderUpdate'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderRead'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/matches/:
    get:
      tags:
      - matches
      summary: Get Matches
      operationId: get_matches_api_v1_matches__get
      parameters:
      - name: limit
        in: query
        required: false
        schema:
          type: integer
          maximum: 50
          minimum: 1
          default: 20
          title: Limit
      - name: offset
        in: query
        required: false
        schema:
          type: integer
          maximum: 10
          minimum: 0
          default: 0
          title: Offset
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MatchRead'
                title: Response Get Matches Api V1 Matches  Get
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/v1/insights/:
    post:
      tags:
      - insights
      summary: Create Insight
      operationId: create_insight_api_v1_insights__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InsightCreate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InsightRead'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /health:
    get:
      summary: Health
      operationId: health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    InsightCreate:
      properties:
        match_id:
          type: integer
          title: Match Id
        text:
          type: string
          title: Text
        price:
          type: integer
          title: Price
      type: object
      required:
      - match_id
      - text
      - price
      title: InsightCreate
    InsightRead:
      properties:
        id:
          type: integer
          title: Id
        order_id:
          type: integer
          title: Order Id
        match_id:
          type: integer
          title: Match Id
        insider_id:
          type: string
          title: Insider Id
        text:
          type: string
          title: Text
        price:
          type: integer
          title: Price
        transaction_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Transaction Id
        is_paid:
          type: boolean
          title: Is Paid
      type: object
      required:
      - id
      - order_id
      - match_id
      - insider_id
      - text
      - price
      - is_paid
      title: InsightRead
    MatchRead:
      properties:
        id:
          type: integer
          title: Id
        order_id:
          type: integer
          title: Order Id
        insider_id:
          type: string
          title: Insider Id
        score:
          type: number
          title: Score
        is_synced:
          type: boolean
          title: Is Synced
      type: object
      required:
      - id
      - order_id
      - insider_id
      - score
      - is_synced
      title: MatchRead
    OrderCreate:
      properties:
        title:
          type: string
          title: Title
        text:
          type: string
          title: Text
      type: object
      required:
      - title
      - text
      title: OrderCreate
    OrderRead:
      properties:
        id:
          type: integer
          title: Id
        title:
          type: string
          title: Title
        text:
          type: string
          title: Text
        client_id:
          type: string
          title: Client Id
        inquiry_id:
          anyOf:
          - type: integer
          - type: 'null'
          title: Inquiry Id
        status:
          type: string
          title: Status
        created_at:
          type: string
          format: date-time
          title: Created At
      type: object
      required:
      - id
      - title
      - text
      - client_id
      - status
      - created_at
      title: OrderRead
    OrderUpdate:
      properties:
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
        text:
          anyOf:
          - type: string
          - type: 'null'
          title: Text
      type: object
      title: OrderUpdate
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
