services:
  prometheus:
    image: prom/prometheus:v3.12.0
    container_name: prometheus
    user: root
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.external-url=http://localhost:8080/prometheus/"
      - "--web.route-prefix=/"
    labels:
      prometheus_scrape: "true"
      prometheus_port: "9090"
      co.elastic.logs/enabled: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9090/-/healthy"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: always

volumes:
  prometheus_data:
