import httpx
import asyncio

bios = [
    {"user_id": "user_01", "text": "Spent the last twelve years climbing the corporate ladder in fintech, only to realize I hate the view from the top. I recently traded my tailored suits and endless spreadsheet evaluations for a pair of muddy boots and a small plot of land where I'm attempting to grow heirloom tomatoes. I values quiet mornings, dark coffee, and slow, deliberate conversations. Trying to find a second act that has absolutely nothing to do with maximizing shareholder value."},
    {"user_id": "user_02", "text": "A software engineer who genuinely believes that open-source code can change the world. When I'm not configuring containerized microservices or troubleshooting infrastructure, I'm mentoring student developers at local hackathons. I thrive in chaotic, highly collaborative technical environments and run primarily on green tea and synthwave music. Let's talk about decentralized networks and automated systems."},
    {"user_id": "user_03", "text": "An archivist and classical history nerd who spent most of my twenties living out of a backpack across Eastern Europe. I track down forgotten folk stories and translate old manuscripts. I am deeply analytical but prone to romanticizing the past. I prefer dusty library basements to modern offices and am looking to connect with people who don't mind spending three hours debating ancient trade routes."},
    {"user_id": "user_04", "text": "A freelance copywriter by day and an aspiring sci-fi novelist by night. My brain functions like an internet browser with 40 tabs open at the same time—half of them are frozen, and there's music playing from somewhere I can't find. I love dystopian world-building, structural logic games, and overanalyzing movie plots. Constantly seeking a balance between absolute creative freedom and rigid routine."},
    {"user_id": "user_05", "text": "A data analyst who applies statistical models to literally everything, including my marathon training schedules and macro-nutrient intake. I'm competitive, highly disciplined, and structured to a fault. I don't really understand 'going with the flow,' but I do understand trend lines and predictable outcomes. Looking for challenges that require endurance, precise execution, and logic."},
    {"user_id": "user_06", "text": "A pediatric nurse with a soft spot for stray animals and underdogs. My life revolves around public health, community organizing, and making sure the people around me feel heard and safe. I am a natural mediator who hates conflict but loves deep emotional processing. I spend my weekends volunteering or getting lost in a good psychological thriller novel."},
    {"user_id": "user_07", "text": "A traditional woodworker who values patience, precision, and raw materials. I don't care much for social media trends or fast-paced living. I believe that if a thing is worth making, it is worth making to last a century. I speak when spoken to, appreciate dry humor, and find my peace in the steady rhythm of a hand plane cutting through oak."},
    {"user_id": "user_08", "text": "A laboratory researcher studying microbial ecosystems. I spend 80% of my time staring at petri dishes and the other 20% explaining to my family that no, I am not engineering a bio-weapon. I love scientific anomalies, experimental electronic music, and staying up until 3:00 AM chasing a random hypothesis. I value curiosity far above convention."},
    {"user_id": "user_09", "text": "A yoga instructor and structural interior designer focusing on space optimization and calm aesthetics. I own exactly 45 items of clothing and don't believe in holding onto psychological or physical clutter. I spend my time practicing mindfulness, drinking matcha, and studying architectural minimalism. Looking to design spaces and lives that feel peaceful, light, and essential."},
    {"user_id": "user_10", "text": "A serial entrepreneur who has started three failed startups and one moderately successful e-commerce brand. I'm a visionary storyteller who loves pitching ideas, building MVPs over a single weekend, and networking. I am easily bored by routine maintenance but highly energized by the initial spark of creation. Looking for builders who can handle turning my chaotic brainstorming sessions into reality."}
]

async def seed_db():
    async with httpx.AsyncClient(timeout=60.0) as client:
        for bio in bios:
            response = await client.post("http://localhost:4012/api/v1", json=bio)
            print(f"Created {bio['user_id']}: Status {response.status_code}")
            
asyncio.run(seed_db())