services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/module: "logstash"
      co.elastic.logs/fileset.stdout: "log"
      co.elastic.logs/fileset.stderr: "log"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
      XPACK_MONITORING_ENABLED: "false"
      ELASTICSEARCH: "elasticsearch:9200"
      BEATS_PORT: "5044"
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl -s http://localhost:9600/ | grep -q ''"status":"green"'' || exit 1',
        ]
      interval: 5s
      timeout: 5s
      retries: 5000
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      elasticsearch:
        condition: service_healthy
