input {
  beats {
    port => "${BEATS_PORT}"
  }
}

filter {
  # If it's an Nginx log, remove the duplicate field so the ES pipeline doesn't crash
  if [event][module] == "nginx" {
    mutate {
      remove_field => [ "[event][original]" ]
    }
  }
}

output {
  elasticsearch {
    # hosts => ["http://mitmproxy:8200"]
    # 
      # - ELASTICSEARCH="elasticserach:9200"
    hosts => ["http://${ELASTICSEARCH}"]
    # 1. Use the data stream name from Filebeat metadata
    index => "%{[@metadata][beat]}-%{[@metadata][version]}"
    
    # 2. MANDATORY for Data Streams
    action => "create"
    
    # 3. Ensure the Nginx pipeline is applied
    pipeline => "%{[@metadata][pipeline]}"
}
}
