services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_password
      - GF_METRICS_ENABLED=true
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:8080/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/alerting:/etc/grafana/provisioning/alerting
      - ./dashboards:/var/lib/grafana/dashboards
    secrets:
      - grafana_password
      - grafana_discord_webhook
    labels:
      prometheus_scrape: true
      prometheus_port: 3000
      co.elastic.logs/enabled: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

secrets:
  grafana_password:
    file: ../../secrets/grafana_password
  grafana_discord_webhook:
    file: ../../secrets/grafana_discord_webhook

    # depends_on:
    #   - prometheus
