openapi: 3.1.0
info:
  title: Identity Service API
  description: Microservice for User Registration and Authentication
  version: 1.0.0
paths:
  /health:
    get:
      summary: Health
      operationId: health_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /soul:
    post:
      summary: Create Soul
      operationId: create_soul_soul_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SoulCreate'
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SoulRead'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /soul/{soul_id}:
    get:
      summary: Read Soul
      operationId: read_soul_soul__soul_id__get
      parameters:
      - name: soul_id
        in: path
        required: true
        schema:
          type: integer
          title: Soul Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SoulRead'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /inquiries:
    post:
      summary: Create Inquiry
      operationId: create_inquiry_inquiries_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InquiryCreate'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /test-scores:
    post:
      summary: Test Receiver
      description: "Temporary test endpoint to catch and log the top 5 scores \ndispatched\
        \ from our background worker."
      operationId: test_receiver_test_scores_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    InquiryCreate:
      properties:
        inquiry_text:
          type: string
          title: Inquiry Text
        uid:
          type: string
          title: Uid
        order_id:
          type: string
          title: Order Id
      type: object
      required:
      - inquiry_text
      - uid
      - order_id
      title: InquiryCreate
    SoulCreate:
      properties:
        bio_essay:
          type: string
          title: Bio Essay
        uid:
          type: string
          title: Uid
      type: object
      required:
      - bio_essay
      - uid
      title: SoulCreate
    SoulRead:
      properties:
        bio_essay:
          type: string
          title: Bio Essay
        uid:
          type: string
          title: Uid
        id:
          type: integer
          title: Id
      type: object
      required:
      - bio_essay
      - uid
      - id
      title: SoulRead
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
