services:
  # --- THE DATABASE ---
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=ledger_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ledger_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # --- THE LEDGER SERVICE ---
  ledger:
    build: .
    container_name: ledger
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=ledger_user
      - DB_NAME=ledger_db
      - DB_PASSWORD=password
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://ledger_user:password@postgres:5432/ledger_db
    depends_on:
      - postgres
    networks:
      - backend

# --- THE DEFINITIONS ---
volumes:
  postgres_data:

networks:
  backend:
    name: ft_transcendence_default
    external: true