services:
  web:
    build: .
    container_name: web
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres # Docker Compose service name
      - DB_PORT=5432 # Default PostgreSQL port
      - DB_USER=web_user
      - DB_NAME=web
    volumes:
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    restart: always
    secrets:
      - postgres_web_pass
    depends_on:
      - postgres # Add this if you have a postgres service

secrets:
  postgres_web_pass:
    file: ../secrets/postgres_web_pass
